spring.application.name=refuge-animalier

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
cors.allowed-origins=${ALLOWED_ORIGINS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

logging.level.org.springframework.jdbc.core=DEBUG